name: Data Extraction

on:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Data Extraction
        run: python extract.py
