name: Data Transformation Benchmarking and Compression

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark-transformations:
    name: Benchmark Data Transformations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Benchmark Script
        run: |
          python benchmark_transformations.py

  clean-and-compress:
    name: Clean and Compress Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Compression Script
        run: |
          python clean_and_compress.py
